document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("<meta charset=\"utf-8\">");
document.writeln("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
document.writeln("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("<meta name=\"description\" content=\"\">");
document.writeln(" <meta name=\"author\" content=\"\">");
document.writeln("<link rel=\"icon\" href=\"http://blog.deweyblog.com/favicon.ico\">");
document.writeln(" <title>My Travel</title>");
document.writeln(" <link href=\"http://blog.deweyblog.com/css/bootstrap.min.css\" rel=\"stylesheet\">");
document.writeln("<link href=\"http://blog.deweyblog.com/css/ie10-viewport-bug-workaround.css\" rel=\"stylesheet\">");
document.writeln("<!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->");
document.writeln("<script src=\"http://blog.deweyblog.com/js/ie-emulation-modes-warning.js\"></script>");
document.writeln("<!--[if lt IE 9]>");
document.writeln("<script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>");
document.writeln("<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>");
document.writeln(" <![endif]-->");
document.writeln(" <link href=\"http://blog.deweyblog.com/css/carousel.css\" rel=\"stylesheet\">");
document.writeln(" <link href=\"http://blog.deweyblog.com/css/article.css\" rel=\"stylesheet\">");
document.writeln("</head>");
document.writeln("<!-- NAVBAR ");
document.writeln("===================================== ============= --> ");
document.writeln("<body>");
document.writeln("<div class=\"navbar-wrapper\">");
document.writeln("<div class=\"container\">");
document.writeln("<nav class=\"navbar navbar-inverse navbar-static-top\">");
document.writeln("<div class=\"container\">");
document.writeln("<div class=\"navbar-header\">");
document.writeln(" <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">");
document.writeln("<span class=\"sr-only\">Toggle navigation</span>");
document.writeln("<span class=\"icon-bar\"></span>");
document.writeln("<span class=\"icon-bar\"></span>");
document.writeln("<span class=\"icon-bar\"></span>");
document.writeln("</button>");
document.writeln("<a class=\"navbar-brand\" href=\"http://blog.deweyblog.com/index.html\">自在·独行</a>");
document.writeln("</div>");
document.writeln("<div id=\"navbar\" class=\"navbar-collapse collapse\">");
document.writeln("<ul class=\"nav navbar-nav\">");
document.writeln("<li class=\"active\"><a href=\"http://blog.deweyblog.com/index.html\">首页</a></li>");
document.writeln("<li class=\"dropdown\">");
document.writeln("<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">攻略游记 <span class=\"caret\"></span></a>");
document.writeln("<ul class=\"dropdown-menu\">");
document.writeln("<li class=\"dropdown-header\">攻略</li>");
document.writeln("<li><a href=\"http://blog.deweyblog.com/children/strategy/taishan.html\">泰山攻略之昼</a></li>");
document.writeln("<li><a href=\"http://blog.deweyblog.com/children/strategy/taishannight.html\">泰山攻略之夜</a></li>");
document.writeln("<li><a href=\"http://blog.deweyblog.com/children/strategy/huashan.html\">华山攻略</a></li>");
document.writeln("<li><a href=\"#\">黄山攻略</a></li>");
document.writeln("<li><a href=\"#\">山西平遥攻略</a></li>");
document.writeln("<li><a href=\"http://blog.deweyblog.com/children/strategy/hexizoulang.html\">河西走廊攻略</a></li>");
document.writeln("<li role=\"separator\" class=\"divider\"></li>");
document.writeln("<li class=\"dropdown-header\">游记</li>");
document.writeln("<li><a href=\"#\">泰山游记</a></li>");
document.writeln("<li><a href=\"#\">华山游记</a></li>");
document.writeln("<li><a href=\"#\">黄山游记</a></li>");
document.writeln("<li><a href=\"#\">长岛游记</a></li>");
document.writeln("<li><a href=\"#\">河西走廊游记</a></li>");
document.writeln("</ul>");
document.writeln("</li>");
document.writeln("<li><a href=\"http://blog.deweyblog.com/children/aboutMe/aboutme.html\">关于我</a></li>");
document.writeln("<li><a href=\"http://blog.deweyblog.com/children/laboratory/index.html\">实验室</a></li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</nav>");
document.writeln("</div>");
document.writeln("</div>");

var url='http://blog.deweyblog.com';
function getUrl(){
    return url;
}